# TCL File Generated by Component Editor 17.1
# Thu Mar 28 13:49:36 EDT 2024
# DO NOT MODIFY


# 
# my_aes_ip "my_aes_ip" v1.0
# Dev mistry 2024.03.28.13:49:36
# Lab 4 IP for a custom AES coprocessor
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module my_aes_ip
# 
set_module_property DESCRIPTION "Lab 4 IP for a custom AES coprocessor"
set_module_property NAME my_aes_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Custom Functions"
set_module_property AUTHOR "Dev mistry"
set_module_property DISPLAY_NAME my_aes_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

