# TCL File Generated by Component Editor 17.1
# Thu Mar 28 14:01:38 EDT 2024
# DO NOT MODIFY


# 
# my_aes128_ip "my_aes128_ip" v1.0
#  2024.03.28.14:01:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module my_aes128_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME my_aes128_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME my_aes128_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL my_aes_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_aes128_ip.v VERILOG PATH my_aes128_ip.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter S0 INTEGER 0
set_parameter_property S0 DEFAULT_VALUE 0
set_parameter_property S0 DISPLAY_NAME S0
set_parameter_property S0 TYPE INTEGER
set_parameter_property S0 ENABLED false
set_parameter_property S0 UNITS None
set_parameter_property S0 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S0 HDL_PARAMETER true
add_parameter S1 INTEGER 1
set_parameter_property S1 DEFAULT_VALUE 1
set_parameter_property S1 DISPLAY_NAME S1
set_parameter_property S1 TYPE INTEGER
set_parameter_property S1 ENABLED false
set_parameter_property S1 UNITS None
set_parameter_property S1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S1 HDL_PARAMETER true
add_parameter S2 INTEGER 2
set_parameter_property S2 DEFAULT_VALUE 2
set_parameter_property S2 DISPLAY_NAME S2
set_parameter_property S2 TYPE INTEGER
set_parameter_property S2 ENABLED false
set_parameter_property S2 UNITS None
set_parameter_property S2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S2 HDL_PARAMETER true
add_parameter S3 INTEGER 3
set_parameter_property S3 DEFAULT_VALUE 3
set_parameter_property S3 DISPLAY_NAME S3
set_parameter_property S3 TYPE INTEGER
set_parameter_property S3 ENABLED false
set_parameter_property S3 UNITS None
set_parameter_property S3 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S3 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point aps_s0
# 
add_interface aps_s0 apb end
set_interface_property aps_s0 associatedClock clock
set_interface_property aps_s0 associatedReset reset
set_interface_property aps_s0 ENABLED true
set_interface_property aps_s0 EXPORT_OF ""
set_interface_property aps_s0 PORT_NAME_MAP ""
set_interface_property aps_s0 CMSIS_SVD_VARIABLES ""
set_interface_property aps_s0 SVD_ADDRESS_GROUP ""

add_interface_port aps_s0 aps_s0_paddr paddr Input 4
add_interface_port aps_s0 aps_s0_psel psel Input 1
add_interface_port aps_s0 aps_s0_penable penable Input 1
add_interface_port aps_s0 aps_s0_pwrite pwrite Input 1
add_interface_port aps_s0 aps_s0_pwdata pwdata Input 32
add_interface_port aps_s0 aps_s0_prdata prdata Output 32
add_interface_port aps_s0 aps_s0_pready pready Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1

